{{- if (default .Values.ingress.enabled .Values.ingress.gateway.enabled) -}}
{{- $fullName := printf "%s-gateway" (include "ipfs.fullname" .) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
  {{- with (default .Values.ingress.annotations .Values.ingress.gateway.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.gateway.host | default .Values.ingress.host | required "please provide a hostname for the ingress" | quote }}
      secretName: {{ .Values.ingress.gateway.secretName | default .Values.ingress.secretName | default (printf "%s-tls" $fullName) }}
  rules:
    - host: {{ .Values.ingress.gateway.host | default .Values.ingress.host | quote }}
      http:
        paths:
          - path: /ipfs
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end -}}
