apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}-cluster-swarm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
spec:
  type: {{ .Values.cluster.service.swarm.type }}
  ports:
    - port: {{ .Values.cluster.service.swarm.port }}
      targetPort: cluster-swarm
      protocol: TCP
      name: cluster-swarm
  {{- if .Values.cluster.service.swarm.ipAddress }}
  loadBalancerIP: {{ .Values.cluster.service.swarm.ipAddress | quote }}
  {{- end }}
  selector:
    {{- include "ipfs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
