apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}-cluster-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
spec:
  type: {{ .Values.cluster.service.api.type }}
  ports:
    - port: {{ .Values.cluster.service.api.port }}
      targetPort: cluster-api
      protocol: TCP
      name: cluster-api
  {{- if .Values.cluster.service.api.ipAddress }}
  loadBalancerIP: {{ .Values.cluster.service.api.ipAddress | quote }}
  {{- end }}
  selector:
    {{- include "ipfs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
