ingress:
  gateway:
    enabled: true
    host: "ipfs.localhost"
  api:
    enabled: true
    host: "ipfs.localhost"
cluster:
  enabled: true
  restApiCredentials: foo:supersecure
  configuration:
    cluster:
      consensus: raft
      replication_factor_min: 1
replicas: 1
# service:
#   swarm:
#     - type: ClusterIP
#       port: 4001
#       ipAddress: null
#     - type: ClusterIP
#       port: 4001
#       ipAddress: null
#     - type: ClusterIP
#       port: 4001
#       ipAddress: null
metrics:
  enabled: true
global:
  dev: true
apiProxy:
  enabled: true
  auth: true
  users:
    foo: bar
  explicitEndpoints: true
  endpoints:
    - /api/v0/pin/add
    - /api/v0/pin/ls
    - /api/v0/pin/verify
    - /api/v0/add
    - /api/v0/get
    - /api/v0/ls
